### PR TITLE
PID pull request

### PR DESCRIPTION
**Pull request by Gabor7697**

### CODE REVIEW

**Comment by gergelytakacs** [comment]
1.  Why does the function need an argument for inputs? Wouldn't it be better to hide this? After all, this is just to remember the previous step...   In my opinion, the PID function shall not need the input as an argument.
2. Also, have you researched (the group, it should not be just the problem of @Gabor7697 ) ways to implement anti-wind up? Of course this works, but have you actually looked up some alternates and methods?

**Comment by Gabor7697** [comment]
According to  http://brettbeauregard.com/blog/2011/04/improving-the-beginner%e2%80%99s-pid-derivative-kick/ if we use the input/last input combination instead of error/last error it removes derivative kick (output spikes) that is why we need input as a function argument. I think both pid and pid1 can be part of the AutomationShield library, so the user can decide. Anti-windup is based on the PID library: http://brettbeauregard.com/blog/2011/04/improving-the-beginner%e2%80%99s-pid-reset-windup/ .

**Comment by mgulan** [comment]
I get the “derivative on meaurement” that you included, but it does not neccessarily have to be desired in any control application. Maybe it should be available by request only (or you add it after it proves to be helpful in most cases).
Similarly, I have seen in practice they often use “proportional on measurement” instead of error...

**Comment by gergelytakacs** [comment]
@kulho - you have essentially "overwritten" and ruined @Gabor7697 's work. We can go back to Gabor's last commit, but this is not a good way to use GiT. You should've made your own branch!

**Comment by gergelytakacs** [comment]
@kulho You can always test controllers in simulation! Take any discrete model and use it to test the PID!:)

**Pull request merged**
