### PR TITLE
FloatShield Update

### PR DESCRIPTION
**Pull request by PeterChmurciak**
@gergelytakacs The swich to Pololu library seems to be sucessful. There has been enough changes in this branch so I would like for Mr.Travis-CI to check if all the changes are compatible and compilable.

### CODE REVIEW

**Comment by PeterChmurciak** [comment]
@gergelytakacs I think Mr.Travis-CI is a bully... According to him none of the examples of any of the Shields can be compiled because of my changes...

**Comment by gergelytakacs** [comment]
On the contrary, sir! Travis CI is a great tool, for example it caught me messing up some of the header files yesterday, that's why none of the boards were building. Yet, it still does fail, so I'm going to investigate now why.

**Comment by gergelytakacs** [comment]
image

Oh yeah, you've created an Auto and Manual version too. Now Mr. Travis (who is definitely not a bully) is configured in `.travis.yml`, that's where it says what examples should be compiled and with what platforms. Changing it now.

**Comment by PeterChmurciak** [comment]
@gergelytakacs You can merge, I am trying to unify them right now, but I have run into some problems. I will commit unified version when done.

**Comment by gergelytakacs** [comment]
@PeterChmurciak I have merged, just open a new PR when done. No hurry or worries!:) 

Then I suggest you open (and self-merge) a PR back from the master to FloatShield so you have up to date code. Alternatively (or even better) just delete the current branch and create new ones, maybe more application specific ones... (FloatShield-matlab) etc. Up to you.

**Pull request merged**
