### PR TITLE
Tibko's version

### PR DESCRIPTION
**Pull request by gergelytakacs**
Merge Tibko to master.

### CODE REVIEW

**Comment by gergelytakacs** [comment]
@TiborKonkoly 
* The initialization of OptoShield should not be PIN dependent. The hardware is given anyway, why should there be such an option begin(pin 1, etc.).  Just use begin(void) and the pin numbers as #defines.
* Pin assignments for different boards should be hard-coded to the header as #defines.
* You have to think about the units of inputs and outputs. I suggest PWM levels as input (but change float to int, we have a control system) and Voltage at the LDR....

**Comment by TiborKonkoly** [comment]
Done :)

2018-03-26 17:17 GMT+02:00 Gergely Takács <notifications@github.com>:

**Comment by gergelytakacs** [comment]
Okay, this is exactly what I meant.

Now, I'm still unsure about the naming conventions and what units should we use.

- should the user see the "raw" sensor data or Volts? Percents?  Should we decide on what units to use in the trainer or should the user have options for this (separate functions....)

**Comment by TiborKonkoly** [comment]
In my opinion, it is easier (at least for me)  to write it using "raw"
material or adc units as output. But I can write functions using normal
units like Volts, Amperes or revolutions. It depends on Your expectations,
what you  expect  from the library and what you expect from the student.

2018-03-26 22:05 GMT+02:00 Gergely Takács <notifications@github.com>:

**Pull request merged**
