### PR TITLE
Update of Simulink files.

### PR DESCRIPTION
**Pull request by cenculis**
Everything should be ready and in working condition.

### CODE REVIEW

**Comment by cenculis** [comment]
no idea why the matlab is not working...

**Comment by gergelytakacs** [comment]
> no idea why the matlab is not working...

Don't worry about that that hasn't worked before.

**Comment by gergelytakacs** [comment]
> Everything should be ready and in working condition.

Good job @cenculis , make sure you keep your thesis reviewer happy:) I will check the PR soon!

**Review by gergelytakacs — APPROVED** [review]
As I can't test the code, I trust you you have done so yourself:)

**Pull request merged**
