### PR TITLE
AeroShield empc

### PR DESCRIPTION
**Pull request by erik1392**

### CODE REVIEW

**Review by AnnaVargova — APPROVED** [review]

**Review by xboldocky — DISMISSED** [review]

**Comment by gergelytakacs** [comment]
@erik1392  Please fix the *.py file for formal errors seen in the codefactor analysis...

**Review by gergelytakacs — CHANGES_REQUESTED** [review]
Fix *.py so that the tabs are fixed (if possible)

**Comment by gergelytakacs** [comment]
Check #359 before this and please try to add the AeroShield to the MATLAB smoke test matrix in build_Matlab to see if it works.

**Comment by gergelytakacs** [comment]
Possibly try to fix spelling errors: 
image

**Comment by gergelytakacs** [comment]
@erik1392  See comments above;)

**Comment by gergelytakacs** [comment]
@erik1392 Sorry to poop your PR, but it seams that the branch breaks something with MATLAB. It has effect on the Floatshield as well, please check out the CI build for MATLAB:
https://github.com/gergelytakacs/AutomationShield/actions/runs/6298023739/job/17096102521?pr=358
(You can run "build_matlab.m" to debug locally)
image

**Review by AnnaVargova — APPROVED** [review]

**Review by gergelytakacs — APPROVED** [review]

**Pull request merged**
